### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty-tcnative#104]
I would like to propose removing all code that we not need for netty (like `Socket`, `Multicast` and many more). We are only interested in the parts that are needed for our OpenSslEngine anyway. This will help us to focus on things we care about and not ship things that we are not using.

@nmittler @Scottmitch @trustin WDYT ?

**Comment by trustin** [comment]
+1

**Comment by nmittler** [comment]
+1

**Comment by Scottmitch** [comment]
+1. I think tcnative "upstream" has rebased off of our code anyways, which may make taking updates a bit more complicated but I'm not sure if we plan on taking updates.

**Comment by normanmaurer** [comment]
Ok will take care of this

**Comment by nmittler** [comment]
@normanmaurer did these commits make it into the 1.1.33 branch? I don't see them in the history

**Comment by normanmaurer** [comment]
@nmittler nope... I need to rebase it figure out what I broke ;)

**Comment by nmittler** [comment]
ah ok sgtm

**Comment by davidben** [comment]
I started poking at this myself. (I'd rather you all not hard-code the values of `SSL_OP_*` constants and figured I ought to get dead code out of the way before tackling that.) GitHub's diff viewer is really slow on that patch and I'm not sure how to download it to be sure, but I think the issue is you removed `tcn_ThrowAPRException` which is called a lot in `ssl.c`. That, in turn, requires that `Error.java` stay there.
