### ISSUE TITLE
Consider merging with Android Conscrypt

### ISSUE THREAD

**Issue by louiscryan** [netty/netty-tcnative#114]
@normanmaurer 
@gregw (for Jetty)
@kruton (for Conscrypt)

Conscrypt is an Apache 2 Licensed JSSE provider built on top of boringssl that has been developed by the Android team. It has had a non-trivial amount of tire-kicking and is used with OpenJDK on the server side at Google. 

Merging efforts here would offer some major upside to the Java development community. 

https://android.googlesource.com/platform/external/conscrypt/+/master

Even if they don't merge, having a solid alternative JSSE provider easily available would benefit lots of folks

**Comment by gregw** [comment]
The jetty project is not yet using tcnative, but are considering it.
We also note that netty is using jetty alpn and are in the process of contributing an alpn agent to that effort.

All in all, since the JVM does not appear to be about to provide a complete and scalable solution any time soon,  perhaps all these efforts should converge somewhere?

We'll give tcnative a go in the next few weeks, at least so we are more informed about all the alternatives.

**Comment by nmittler** [comment]
FYI @davidben, you may be interested in this as well.

**Comment by gregw** [comment]
Jetty had a look at tcnative, but it is too far off the reservation for us to consider using.   Not yet had a chance to look at conscrypt, but if it is JSSE compliant, that may be a better option for us.

we have in the meantime implemented native unix socket support so that we can use something like haproxy to offload ssl

**Comment by normanmaurer** [comment]
@gregw what you mean with "far off the reservation" ? Can you elaborate a bit ?

Also do you have a link to your unix socket support ? We support it as well in netty but only for linux atm.

**Comment by johnou** [comment]
@normanmaurer Aussie slang for not viable.

**Comment by gregw** [comment]
@normanmaurer I've corrected my language.

Our unix-socket implementation is [here](https://github.com/eclipse/jetty.project/tree/jetty-9.4.x/jetty-unixsocket), it too is only for linux.

**Comment by normanmaurer** [comment]
@gregw gotcha... thanks :)

**Comment by perezd** [comment]
Any movement on this? Has this died? I'm trying to personally make sense of how all these dependencies currently fit into netty:
https://stackoverflow.com/questions/45852625/design-architecture-of-nettys-handler-ssl-package

**Comment by ejona86** [comment]
@perezd, yes, there's been progress. There's been Conscrypt support added to Netty and Conscrypt [has a website](http://conscrypt.org/) and the performance of the SSLEngine was improved a lot (based on tcnative; Android doesn't use SSLEngine much).

Conscrypt now has [artifacts on Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.conscrypt%22), and is _very_ close to a 1.0 release. I'm not sure there's a long-term plan of figuring out the future of netty-tcnative (given Conscrypt's soon availability), but it'll probably depend on how things work out in the near future.

**Comment by perezd** [comment]
Thanks for the update! 

I'm not sure if this is really the right place to ask this question, but I'm kinda stumped: How does one compile netty properly if tc-native AND conscrypt are both statically including their own versions of BoringSSL. Doesn't this cause some kind of runtime collision/conflict?

**Comment by ejona86** [comment]
I've been able to include tcnative and Conscrypt at runtime, and use each in the same process. The static BoringSSL doesn't cause any problem. Runtime detection is annoying, but if you know exactly what your binary will include it is pretty straight-forward. You mainly just configure Netty's SslContextBuilder to use JDK for Conscrypt or TCNATIVE for tcnative, and specify Conscrypt (`Conscrypt.newProvider()`) as the JDK provider if that's what you're using. There's some other options available (like `java.security.Security.insertProviderAt(Conscrypt.newProvider(), 1)`); we just need to play with Conscrypt more to help determine what works best.

That said, there's still some bumps because Conscrypt has broken its API some in the past couple pre-releases. That shouldn't be an issue after it goes 1.0.

**Comment by perezd** [comment]
Hi there, any progress on this front?

**Comment by normanmaurer** [comment]
@perezd nope

**Comment by Scottmitch** [comment]
The current relationship is Conscrypt generally takes changes we make in netty-tcnative and hopefully we are notified if any issues are discovered (hint hint @nmittler). However maybe consolidation is more viable now that Conscrypt is 1.0.

**Comment by normanmaurer** [comment]
This will not happen... Closing
