### ISSUE TITLE
Non standard project layout

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty-tcnative#118]
Since we have started supporting the static library builds the directory structure is no longer following the standard maven directory structure. This can make discovery and IDE interop more difficult. Is it possible to put the java/c code back to the "top" level so maven can correctly generate IDE project files?

**Comment by Scottmitch** [comment]
Should we also add `boring-ssl-static/src` and `openssl-static/src/` to `.gitignore`?

**Comment by nmittler** [comment]
intellij doesn't seem to be having a problem for me ... what is the problem you're seeing?

**Comment by normanmaurer** [comment]
yeah works for me as well with intellij

**Comment by Scottmitch** [comment]
source sets are not set correctly so Eclipse doesn't know where they are (no entries are add to the `.classpath` file). I would imagine this would happen with any IDE project files generated from maven...it may be different if you import the pom directly into the IDE.  I tried `mvn idea:idea` but it seems this plugin is not supported any more and does not work, so not sure if this is an option for `idea`

Also is the source files for tcnative (java and C) seem to be duplicated during the build:

```
openssl-dynamic/src/main
openssl-static/src/main
boringssl-static/src/main
```

Can you explain why this occurs? Also it seems like the `mvn clean` task does not clean up the "duplicate" sources, how do you clean up the duplicate source files via the build process?

**Comment by nmittler** [comment]
Yeah the static libs copy everything under `src` from `openssl-dynamic`. The main reason for this is that it needs the `native` config files, but has to overwrite the msvc build file with its own ... the easiest solution: copy everything, then overwrite the copied msvc file. We could copy to the target folder, and treat all of this as "generated-sources" so that clean just automatically works. Alternatively, we could configure the static libs so they remove src when they clean.

**Comment by Scottmitch** [comment]
It is still not clear to my why the copy operation for the tcnative source code is necessary. However assuming it is necessary can we do something like you suggested:

- Revert directory structure back to maven standard
- Copy code during build process to a `target/` type directory that gets cleaned up with other build artifacts.

**Comment by nmittler** [comment]
As far as I know the copy is necessary.  Maven essentially gives us 2 options for reusing code:

1. Point the source directory for xxx-static to openssl-dynamic/src.  The problem here is that it will pick up the native dir with the "bad" msvc file. We need everything except that msvc file.
2. Copy the source and overwrite the msvc file.

If you have ideas for how to better make this conform to the maven standard, feel free to throw together a PR

**Comment by Scottmitch** [comment]
Although copying is not ideal, this is not the issue. The issues are:

- non-standard maven directory structure. This makes life difficult for tools and general orientation in the project.
- `n` (number of builds) replicas of the source code which are generated during the build and not cleaned up as part of the build. This can also be confusing when in an IDEs and looking at the file structure after a build (`find . -name "ssl.c" | xarsg grep "mymethod"`) ... you have to reference git to know which source file is the source of truth.
