### ISSUE TITLE
Uber jars on maven central are missing native libraries

### ISSUE THREAD

**Issue by nmittler** [netty/netty-tcnative#145]
The uber jar (i.e. the one without a classifier) for both fork 16 and 17 on Maven Central does not contain the `META-INF/native` folder.  We're either not building the jar properly or there is a problem with how we're pushing it to Maven Central.

**Comment by nmittler** [comment]
@normanmaurer can you take a look?

**Comment by baldrick** [comment]
I think (at least Fork17) _does_ contain a `META-INF/native` folder but the libraries are named so they're unusable.  Fork 17 contains (among others):

```
META-INF/native/netty-tcnative-windows-x86_64.dll
META-INF/native/libnetty-tcnative-osx-x86_64.jnilib
META-INF/native/libnetty-tcnative-linux-x86_64.so
```

But looking at `io.netty.util.internal.NativeLibraryLoader.load()` we can see it calls `System.mapLibraryName(name)` where `name` is `netty-tcnative`.  It returns:

- `netty-tcnative.dll` on Windows
- `libnetty-tcnative.so` on Linux

Both platforms (I haven't tried OSX) therefore fail to find the _-{os}-{arch}_ classified library from `META-INF/native` and therefore throw `java.lang.UnsatisfiedLinkError: no netty-tcnative in java.library.path`.

The _classified_ versions of Fork17 work because they contain libraries that match the name returned by `System.mapLIbraryName()`:

- `netty-tcnative-boringssl-static-1.1.33.Fork17-windows-x86_64.jar` contains `META-INF/native/netty-tcnative.dll`
- `netty-tcnative-boringssl-static-1.1.33.Fork17-linux-x86_64.jar` contains `META-INF/native/libnetty-tcnative.so`

There are a couple of options I can think of:

1. Rename the libs included in the uber jar so they match `System.mapLibraryName()` output
  - AFAIK this would mean you can't ship 32-bit and 64-bit libraries in the same uber jar though
2. Inject appropriate _-{os}-{arch}_ classifiers into the output of `System.mapLibraryName()` (in a similar fashion to the rewriting done for OSX)

**Comment by nmittler** [comment]
Hmm ... I'm confused.  I just downloaded the jar again from repo1 (https://repo1.maven.org/maven2/io/netty/netty-tcnative/1.1.33.Fork17/netty-tcnative-1.1.33.Fork17.jar) and it does not contain `META-INF/native'. Perhaps there are some replication issues in Maven Central?

WRT the Netty code, [OpenSsl](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L230) iterates over some options for the library name, where the last option in the list is the fallback to `netty-tcnative`.  I believe this was introduced in Netty `4.1.0-CR4`. Which version of Netty are you using?

**Comment by normanmaurer** [comment]
@nmittler maybe I`m confused now as well but shouldn`t you download:

https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/1.1.33.Fork17/netty-tcnative-boringssl-static-1.1.33.Fork17.jar

**Comment by nmittler** [comment]
![](http://i.imgur.com/iWKad22.jpg) ... sorry, yes. And it has all the libs expected.

baldrick@ what version of Netty are you using?

**Comment by baldrick** [comment]
I don't depend directly on `io.netty/netty`, only `netty-tcnative`.
However I do depend upon `io.grpc/grpc-all/0.13.2` which, according to `mvn dependency:tree`, pulls in `io.netty/netty-handler/4.1.0.CR3`.

Upgrading to `io.grpc/grpc-all/0.14.0` (is this the latest?  maven central's blocked at work so I have to rely on an internal mirror that may or may not be up to date...) brings in `io.netty/netty-handler/4.1.0.CR7` ... which has solved this problem :smile: ... although my one-off test before I go home hints it may be significantly slower.  But that's a one-off... I hope.

I suggest this issue can therefore be closed.

**Comment by nmittler** [comment]
Ok thanks baldrick@ .. closing for now.  If you decide there is a perf issue feel free to open a new bug.
