### ISSUE TITLE
Review usage of BoringSSL return values

### ISSUE THREAD

**Issue by nmittler** [netty/netty-tcnative#179]
Some functions claim a narrower set of return values in BoringSSL than OpenSSL.  The BoringSSL team generally dislikes the -1/0/1 return and switched to 0/1 where feasible.

We should go through the code and make sure we correctly handle the return codes for both BoringSSL and OpenSSL.

**Comment by Scottmitch** [comment]
+1. Thanks for reporting @nmittler! This seems like a bit of a manual process ... I wonder if there is a list of methods where return semantics may have "changed" that we can use to search our code with?

**Comment by nmittler** [comment]
Good question.  @davidben any thoughts on how we might speed up our search?

**Comment by nmittler** [comment]
Ah ok, thanks for clarifying.  I guess this should be a no-op then. Closing for now.

**Comment by Scottmitch** [comment]
thanks for clarifying @davidben ... just to clarify BoringSSL still tolerates `-1` being returned from callback backs in the same way OpenSSL does, correct? If we can still use `== 1` (or `!=1`) to check for success then we should be ok.

**Comment by davidben** [comment]
That's right. It would be a nightmare for us if third-party code targeting OpenSSL did not work with BoringSSL, so we're not going to change the meaning of callbacks on consumers. :-)

I think most of the stuff where callbacks (or `BIO`s) are involved, 0 vs -1 is actually significant, so we haven't done much to the return codes. BoringSSL's `SSL_read` still has the same complex dance that OpenSSL's has.

It's more functions in libcrypto where the distinction between 0, -1, (and sometimes even -2!) was basically meaningless that we'd narrow. Turns out you can basically narrow the entire crypto stack without losing fidelity.

**Comment by normanmaurer** [comment]
@danbev thanks for the details :) And yay for closing @nmittler =P
