### ISSUE TITLE
Support to Tomcat

### ISSUE THREAD

**Issue by matejsp** [netty/netty-tcnative#297]
I understood that this is a fork from tomcat native with additional support for couple of very nice features like mavenization, non static compilation and support for other crypto libraries. However when I tried it using tomcat it was not working. Can you add it or at least preserve it from upstream.

If this is not the goal of this project then perhaps rename is in order (netty-native instead of netty-tcnative).

**Comment by normanmaurer** [comment]
Yeah sorry this is not the scope... we PLB to merge this code base into netty directly

**Comment by Scottmitch** [comment]
My preference is to move netty-tcnative into Netty. There at one time was little semblance to tomcat, and since this time IIUC they have actually taken our changes into tcnative 2.0. This will help avoid confusion from versioning, relationship to tomcat, and allow for more shared JNI / native library loading code.
