### ISSUE TITLE
Publish uber netty-tcnative jar that supports all platforms to maven

### ISSUE THREAD

**Issue by vrozov** [netty/netty-tcnative#309]
Currently, consumers of netty-tcnative jar make a build time decision what jar to include into dependency using classifier. By providing uber netty-tcnative jar this decision may be deferred to run-time when the actual platform is known.

**Comment by normanmaurer** [comment]
netty-tcnative-boringssl-static does exactly this. Include it without specify the classifier and you have support on macOS, Linux and windows

**Comment by vrozov** [comment]
The request is for the default netty-tcnative library that dynamically links to openSSL.

**Comment by vrozov** [comment]
@normanmaurer Any specific reason that uber jar is not provided for the default library that dynamically links with openssl.

**Comment by vrozov** [comment]
@normanmaurer Any update on this? Any project that wants to utilize openssl-dynamic netty-tcnative library has to 
1. Use maven extension that is not well supported by Eclipse IDE
2. Has to include all {os_arch} into distribution and change startup script to select a proper library at startup.

**Comment by normanmaurer** [comment]
@vrozov while we may could do this this also will complicate releasing etc. I am not feeling very strong to really need this honestly.

 @ejona86 @Scottmitch @carl-mastrangelo @Scottmitch what is your take on this ?

**Comment by vrozov** [comment]
@normanmaurer why will it complicate the release if you already do it for netty-tcnative-boringssl-static?

**Comment by ejona86** [comment]
@vrozov, could you explain a bit more about your environment/use-case?

boringssl-static doesn't have the problem with Fedora vs Debian. Right now the dynamic version uses the same name between those two. But [I _think_](https://github.com/netty/netty/blob/0fffc844d6d4c8e196a8448a45e7ff542446f708/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L414) that may be solved by just renaming the fedora so.

For Windows and OS X, the binaries don't "just work", as you need to install OpenSSL separately.

So I'm not sure I would understand the use-case for an uber version except for if you only work on Linux machines.

**Comment by vrozov** [comment]
Consider a project (for example Apache Drill) that wants to enable SSL using openssl instead of JDK for the same reason why netty provides openssl/netty-tcnative library and does not always rely on JDK. Now to consume netty-tcnative, it is necessary to complicate maven pom dependency and it still does not solve run-time dependency as during drill build, we do not know run-time OS. 

Requiring openssl to be installed separately is preferable as in such configuration openssl can be patched independently and there is no need to release netty-tcnative and drill patches every time there is a new patch for openssl.

**Comment by ejona86** [comment]
@normanmaurer, given that you can't necessarily upgrade netty-tcnative without also upgrading netty, I think it can make sense to provide something here. Note that with something like Conscrypt, updating in face of vulnerability would be easier.

It would _mostly_ work (assuming fedora .so was renamed) for an application to depend on each of the variations of netty-tcnative, as the .class files will be the same and all the native code would still be found. But I'd agree it's icky and prone to weird failures.

Although OpenSSL requires much more frequent fixes than BoringSSL due to higher feature surface, I do agree it is important to have a strategy for how to deliver those fixes. If your users would actually update OpenSSL, then that can work. Linux and Mac (with brew) is probably fine there.

@normanmaurer, I think the uber jar is sane, although I don't know how much of a PITA it is. I just know I'm well past the point of scared of the build files. There's also the problem that the classifier-less .jar (which is used for static uber jar) for netty-tcnative is pre-existing.

**Comment by vrozov** [comment]
@normanmaurer Is there a final word on the issue?

**Comment by normanmaurer** [comment]
Sorry had no time yet to investigate
