### ISSUE TITLE
Boringssl-static crashes on Elliptic Curve P-521 key and cert chain with BAD_ECC_CERT (works with JDK impl.)

### ISSUE THREAD

**Issue by Moocow9m** [netty/netty-tcnative#456]
Using io.netty:netty-tcnative-boringssl-static:2.0.24.Final

When using a P-521 Key and cert chain I get a BAD_ECC_CERT error.
Works when using JDK impl instead of boringssl impl.
Perhaps Boringssl is ignoring the trust manager?

Server Output: https://pastebin.com/EPesFKT3
Client Output: https://pastebin.com/02fsnGPf
Cert Chain: https://pastebin.com/Gir8iJtz
Cert Chain provided to both client(trustmanager) and server(SSLContextBuilder).
Private key to last cert in chain(binary pkcs8): http://s000.tinyupload.com/index.php?file_id=28618851238157995521

Server Code:

```
ServerBootstrap bootstrap = new ServerBootstrap().group(new NioEventLoopGroup(1), new NioEventLoopGroup()).channel(NioServerSocketChannel.class);
 SslContext context= SslContextBuilder.forServer(privateKey, certificates).sslProvider(SslProvider.OPENSSL).build();
bootstrap = bootstrap.handler(new LoggingHandler(LogLevel.INFO)).childHandler(new ChannelInitializer<SocketChannel>() { @Override public void initChannel(SocketChannel ch) { ChannelPipeline p = ch.pipeline();
 if (context != null) { 
p.addLast(context.newHandler(ch.alloc())); 
} 
p.addLast(new ObjectEncoder(), new ObjectDecoder(104857600,ClassResolvers.cacheDisabled(null))); }
 });
Channel c = b.bind(25789).sync().channel();
```

Client Code:

```
Bootstrap bootstrap = new Bootstrap().group(new NioEventLoopGroup()).channel(NioSocketChannel.class);
 SslContext context= SslContextBuilder.forClient().trustManager(certificates).sslProvider(SslProvider.OPENSSL).build();
bootstrap = bootstrap.handler(new LoggingHandler(LogLevel.INFO)).childHandler(new ChannelInitializer<SocketChannel>() { @Override public void initChannel(SocketChannel ch) { ChannelPipeline p = ch.pipeline();
 if (context != null) { 
p.addLast(context.newHandler(ch.alloc())); 
} 
p.addLast(new ObjectEncoder(), new ObjectDecoder(104857600,ClassResolvers.cacheDisabled(null))); }
 });
Channel c = b.connect("localhost", 25789).sync().channel();
```

**Comment by Moocow9m** [comment]
Perhaps Boringssl is ignoring the trust manager?

**Comment by davidben** [comment]
Er, right, my bad. The low-level crypto bits support P-224, P-256, P-384, and P-521, but the TLS client, by default, will only accept P-256 and P-384, like Chrome and IE.

Do I guess correctly that you are just picking the curve with the largest number? Do not do that. Use P-256.

**Comment by Moocow9m** [comment]
@davidben I am not automatically picking the largest number, I was trying to use ones not supported commonly on purpose. I will lower it.

**Comment by davidben** [comment]
Ah, sorry, my mistake.

It is possible to enable it in BoringSSL, but whether it's worth exposing a Netty option I'll leave to Netty folks. Configuring curves is not that common of a use case, and API surface costs maintenance overhead.

We omit it because we try to keep the set of options supported small, for maintenance and testing reasons. A good implementation of an EC curve is specialized to the curve. Supporting options that aren't needed in practice means people will use them (it's common to just pick the largest number), which in turn means everyone needs to maintain yet more implementations and energy spent on security hardening and performance is diluted.

**Comment by davidben** [comment]
By the way, if your goal is to use uncommon stuff for testing purposes, BoringSSL may not be the library for you. We try to be more minimal so that we only need to maintain the stuff that's actually important. TLS has a history of too many unnecessary options. In many cases, this has had negative security consequences.

**Comment by Moocow9m** [comment]
P-256 and P-384 worked. And thanks for the explanation!
