### ISSUE TITLE
Gradle doesn't like boringssl-static profile pom

### ISSUE THREAD

**Issue by louiscryan** [netty/netty-tcnative#96]
Gradle seems to be a little stricter than maven when resolving artifacts that use classifiers. In particular it doesn't like the fact that the artifact name in the pom being simply 'netty-tcnative' when it has to resolve it in the repo in separate location

* What went wrong:
Execution failed for task ':grpc-benchmarks:extractIncludeProto'.
> Could not resolve all dependencies for configuration ':grpc-benchmarks:compile'.
   > Could not resolve io.netty:netty-tcnative-boringssl-static:1.1.33.Fork12-SNAPSHOT.
     Required by:
         io.grpc:grpc-benchmarks:0.13.0-SNAPSHOT
      > Could not resolve io.netty:netty-tcnative-boringssl-static:1.1.33.Fork12-SNAPSHOT.
         > inconsistent module metadata found. Descriptor: io.netty:netty-tcnative:1.1.33.Fork12-SNAPSHOT Errors: bad module name: expected='netty-tcnative-boringssl-static' found='netty-tcnative'

Will take a look at fixing....

**Comment by nmittler** [comment]
I wonder if switching netty-tcnative to gradle would just fix this.  I'm considering doing this anyway to simplify the configuration (profiles are a pain and require a lot of duplication).

@normanmaurer thoughts?

**Comment by normanmaurer** [comment]
I hate gradle :(

**Comment by nmittler** [comment]
@normanmaurer Agreed, all build environment sucks :).  I'm not a huge advocate of gradle either, but it does have some fairly significant advantages in situations like this.  The profile gunk (which is getting a bit out of hand at the moment) would effectively go away and would be replaced with a fairly simple bit of groovy code to figure out the proper artifactId and build flags.

The alternative is to stick with Maven and either find a way to hack it so that the proper artifactId is set in the metadata, or switch to a multi-module project.  Both seem a little ugly (especially the latter).

It's probably worth taking a crack at this just to see what it might look like.  Does that sound reasonable?
